inherit_gem:
  betterlint:
    - config/default.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 3.2
  TargetRailsVersion: 7.2
  Exclude:
    - gemfiles/*.gemfile

Gemspec/DevelopmentDependencies:
  Enabled: true
  EnforcedStyle: gemspec

Naming/VariableNumber:
  Enabled: true
  AllowedIdentifiers: mysql2
