language: ruby
rvm:
  - 2.4.2
  - 2.6.1
services:
  - mysql
  - postgresql
env:
  - DB_ADAPTER=mysql
  - DB_ADAPTER=postgresql
gemfile:
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_6_0.gemfile
matrix:
  exclude:
  - rvm: 2.4.2
    gemfile: gemfiles/rails_6_0.gemfile
before_install:
  - mysql -e 'SET GLOBAL TRANSACTION ISOLATION LEVEL READ COMMITTED;'
