default: &default
  pool: 50
  timeout: 5000

postgresql:
  development: &pg_default
    <<: *default
    adapter: "postgresql"
    database: "with_transactional_lock_development"
  test: &pg_test
    <<: *default
    adapter: "postgresql"
    username: <%= ENV['POSTGRES_USER'] %>
    host: localhost
    database: "with_transactional_lock_test"

development:
  <<: *pg_default

test:
  <<: *pg_test
