# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c00c0963d17e3a8739e04576d69a1437274f0e023dcb84fb4122b63c3232ef22d6c0db83be94df24f86bf10de043d2fb2cc103d2bad0908621eb637f63d39171

test:
  secret_key_base: 21e08ccda8bb794e1d454fb61879035532c4381aa20663d8406c7ceb849c77c451571596d1540411363f4ba7bbdefe77780f5280bd9885224e5ca3cf60a3ed77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
