name: Linter

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
    - name: Set up Ruby 3.2
      uses: ruby/setup-ruby@a4effe49ee8ee5b8b5091268c473a4628afb5651 # v1
      with:
        ruby-version: 3.2
    - name: Generate lockfile for cache key
      run: bundle lock
    - name: Cache gems
      uses: actions/cache@8492260343ad570701412c2f464a5877dc76bace # v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-linter-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-linter-
    - name: Install gems
      run: |
        bundle config path vendor/bundle
        bundle config set without 'default test'
        bundle install --jobs 4 --retry 3
    - name: Run Linter
      run: bundle exec rubocop --parallel
